spring:

  datasource:
    url: jdbc:mysql://localhost/codingcafe?useSSL=false
    username: codingcafe
    password: codingcafe

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost
      bindings:
        purchases:
          destination: codingcafe.order.purchase
          content-type: application/json
        beverages:
          destination: codingcafe.order.beverage
          content-type: application/json
        foodstuffs:
          destination: codingcafe.order.foodstuff
          content-type: application/json

server:
  port: 9100